/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author gusta
 */
public class Calc extends javax.swing.JFrame {
    
    private String temp = "";
    private String num1, num2;
    private String operacao = "";
    private boolean igualPressionado = false;
    private boolean isInserindoNumero = false;
    private String memoriaCopiar = "";
    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtvisor = new javax.swing.JTextField();
        btback = new javax.swing.JButton();
        btsete = new javax.swing.JButton();
        btquatro = new javax.swing.JButton();
        btum = new javax.swing.JButton();
        btponto = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        btoito = new javax.swing.JButton();
        btcinco = new javax.swing.JButton();
        btdois = new javax.swing.JButton();
        btzero = new javax.swing.JButton();
        btcontrol = new javax.swing.JButton();
        btnove = new javax.swing.JButton();
        btseis = new javax.swing.JButton();
        bttres = new javax.swing.JButton();
        btigual = new javax.swing.JButton();
        btalterna = new javax.swing.JButton();
        btdiv = new javax.swing.JButton();
        btmult = new javax.swing.JButton();
        btsub = new javax.swing.JButton();
        btmais = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemmenucopiar = new javax.swing.JMenuItem();
        itemmenucolar = new javax.swing.JMenuItem();
        itemmenurecortar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setLocationByPlatform(true);
        setResizable(false);

        txtvisor.setEditable(false);
        txtvisor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btback.setText("Bsp");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btsete.setText("7");
        btsete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btseteActionPerformed(evt);
            }
        });

        btquatro.setText("4");
        btquatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquatroActionPerformed(evt);
            }
        });

        btum.setText("1");
        btum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btumActionPerformed(evt);
            }
        });

        btponto.setText(".");
        btponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpontoActionPerformed(evt);
            }
        });

        btclear.setText("CE");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        btoito.setText("8");
        btoito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoitoActionPerformed(evt);
            }
        });

        btcinco.setText("5");
        btcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcincoActionPerformed(evt);
            }
        });

        btdois.setText("2");
        btdois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdoisActionPerformed(evt);
            }
        });

        btzero.setText("0");
        btzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btzeroActionPerformed(evt);
            }
        });

        btcontrol.setText("Crt");
        btcontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcontrolActionPerformed(evt);
            }
        });

        btnove.setText("9");
        btnove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoveActionPerformed(evt);
            }
        });

        btseis.setText("6");
        btseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btseisActionPerformed(evt);
            }
        });

        bttres.setText("3");
        bttres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttresActionPerformed(evt);
            }
        });

        btigual.setText("=");
        btigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btigualActionPerformed(evt);
            }
        });

        btalterna.setText("+/-");
        btalterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalternaActionPerformed(evt);
            }
        });

        btdiv.setText("/");
        btdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdivActionPerformed(evt);
            }
        });

        btmult.setText("x");
        btmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmultActionPerformed(evt);
            }
        });

        btsub.setText("-");
        btsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubActionPerformed(evt);
            }
        });

        btmais.setText("+");
        btmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtvisor, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btponto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btsete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btback, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btclear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btoito, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btdois, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btzero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btcontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnove, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btseis, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttres, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btigual, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btalterna, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btmult, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btsub, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btmais, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btalterna, btback, btcinco, btclear, btcontrol, btdiv, btdois, btigual, btmais, btmult, btnove, btoito, btponto, btquatro, btseis, btsete, btsub, bttres, btum, btzero});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnove, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btseis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btalterna, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmult, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btsub, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btclear)
                            .addComponent(btback)
                            .addComponent(btcontrol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btoito)
                            .addComponent(btsete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btcinco)
                            .addComponent(btquatro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btdois)
                            .addComponent(btum))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btzero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btponto)
                    .addComponent(btigual)
                    .addComponent(btmais))
                .addGap(15, 15, 15))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btalterna, btback, btcinco, btclear, btcontrol, btdiv, btdois, btigual, btmais, btmult, btnove, btoito, btponto, btquatro, btseis, btsete, btsub, bttres, btum, btzero});

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setMnemonic('r');
        jMenu1.setText("Calculadora");

        jMenuItem1.setMnemonic('s');
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('e');
        jMenu2.setText("Editar");

        itemmenucopiar.setMnemonic('c');
        itemmenucopiar.setText("Copiar");
        itemmenucopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenucopiarActionPerformed(evt);
            }
        });
        jMenu2.add(itemmenucopiar);

        itemmenucolar.setMnemonic('a');
        itemmenucolar.setText("Colar");
        itemmenucolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenucolarActionPerformed(evt);
            }
        });
        jMenu2.add(itemmenucolar);

        itemmenurecortar.setMnemonic('t');
        itemmenurecortar.setText("Recortar");
        itemmenurecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmenurecortarActionPerformed(evt);
            }
        });
        jMenu2.add(itemmenurecortar);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('b');
        jMenu3.setText("Sobre");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('i');
        jMenu4.setText("Sair");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
       num1 = "";
       num2 = "";
       operacao = "";
       temp = "";
       igualPressionado = false;
       isInserindoNumero = false;
       txtvisor.setText(temp);
    }//GEN-LAST:event_btclearActionPerformed

    private void btalternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalternaActionPerformed
        if("".equals(temp)){
            return;
        }
        
        if(!temp.startsWith("-")){
            temp = "-"+temp;
        }else{
            temp = temp.substring(1);
        }
        txtvisor.setText(temp);
    }//GEN-LAST:event_btalternaActionPerformed

    private void btnoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoveActionPerformed
       inserirNumero("9");
    }//GEN-LAST:event_btnoveActionPerformed

    private void btpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpontoActionPerformed
        
        inserirNumero(".");
    }//GEN-LAST:event_btpontoActionPerformed

    private void btumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btumActionPerformed
        inserirNumero("1");
    }//GEN-LAST:event_btumActionPerformed

    private void btseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btseteActionPerformed
        inserirNumero("7");
    }//GEN-LAST:event_btseteActionPerformed

    private void inserirNumero(String numero) {
        if(!"".equals(operacao) && !isInserindoNumero){
            temp="";
            isInserindoNumero = true;
        }
        
        if(igualPressionado){
            temp = "";
            igualPressionado = false;
        }
        if("".equals(temp) && ".".equals(numero)){
            temp = "0";
        }
        if(temp.contains(".") && ".".equals(numero)){
            return;
        }
        
        temp += numero;
        txtvisor.setText(temp);
    }

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        if(!"".equals(temp)){
            temp = temp.substring(0, temp.length()-1);
        }
        txtvisor.setText(temp);
    }//GEN-LAST:event_btbackActionPerformed

    private void btoitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoitoActionPerformed
        inserirNumero("8");
    }//GEN-LAST:event_btoitoActionPerformed

    private void btquatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquatroActionPerformed
       inserirNumero("4");
    }//GEN-LAST:event_btquatroActionPerformed

    private void btcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcincoActionPerformed
        inserirNumero("5");
    }//GEN-LAST:event_btcincoActionPerformed

    private void btseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btseisActionPerformed
        inserirNumero("6");
    }//GEN-LAST:event_btseisActionPerformed

    private void btdoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdoisActionPerformed
        inserirNumero("2");
    }//GEN-LAST:event_btdoisActionPerformed

    private void bttresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttresActionPerformed
       inserirNumero("3");
    }//GEN-LAST:event_bttresActionPerformed

    private void btzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btzeroActionPerformed
       inserirNumero("0");
    }//GEN-LAST:event_btzeroActionPerformed

    private void btmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmaisActionPerformed
        ativarOperacao("+");
    }//GEN-LAST:event_btmaisActionPerformed

    private void ativarOperacao(String operacao) {
        igualPressionado = false;
        isInserindoNumero = false;
        if("".equals(this.operacao)){
            if("".equals(temp)){
                return;
            }
            this.operacao = operacao;
            num1 = temp;
        }else{
            double[] d = converte(num1, temp);
            executaCalculo(d, this.operacao);
            this.operacao = operacao;
            txtvisor.setText(temp);
        }
    }

    private void btigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btigualActionPerformed
        num2 = temp;
        double[] d = converte(num1, num2);
        executaCalculo(d, operacao);
        txtvisor.setText(temp);
        operacao = "";
        igualPressionado = true;
    }//GEN-LAST:event_btigualActionPerformed

    private void executaCalculo(double[] d, String operacao) {
        switch(operacao){ 
            case "+":
                num1 = temp = String.valueOf(d[0] + d[1]);
                break;
            case "-":
                num1 = temp = String.valueOf(d[0] - d[1]);
                break;
            case "x":
                num1 = temp = String.valueOf(d[0] * d[1]);
                break;
            case "/":
                num1 = temp = String.valueOf(d[0] / d[1]);
                break;
                
        }
    }

    private void btsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubActionPerformed
        ativarOperacao("-");
    }//GEN-LAST:event_btsubActionPerformed

    private void btmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmultActionPerformed
        ativarOperacao("x");
    }//GEN-LAST:event_btmultActionPerformed

    private void btdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdivActionPerformed
       ativarOperacao("/");
    }//GEN-LAST:event_btdivActionPerformed

    private void btcontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcontrolActionPerformed
        operacao = "";
        temp = num1;
        txtvisor.setText(temp);
    }//GEN-LAST:event_btcontrolActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        new Sobre().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void itemmenucopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenucopiarActionPerformed
        memoriaCopiar = "";
        memoriaCopiar = temp;
    }//GEN-LAST:event_itemmenucopiarActionPerformed

    private void itemmenucolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenucolarActionPerformed
        temp = memoriaCopiar;
        txtvisor.setText(temp);
    }//GEN-LAST:event_itemmenucolarActionPerformed

    private void itemmenurecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmenurecortarActionPerformed
        memoriaCopiar = "";
        memoriaCopiar = temp;
        temp = "";
        txtvisor.setText(temp);
    }//GEN-LAST:event_itemmenurecortarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btalterna;
    private javax.swing.JButton btback;
    private javax.swing.JButton btcinco;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btcontrol;
    private javax.swing.JButton btdiv;
    private javax.swing.JButton btdois;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btmais;
    private javax.swing.JButton btmult;
    private javax.swing.JButton btnove;
    private javax.swing.JButton btoito;
    private javax.swing.JButton btponto;
    private javax.swing.JButton btquatro;
    private javax.swing.JButton btseis;
    private javax.swing.JButton btsete;
    private javax.swing.JButton btsub;
    private javax.swing.JButton bttres;
    private javax.swing.JButton btum;
    private javax.swing.JButton btzero;
    private javax.swing.JMenuItem itemmenucolar;
    private javax.swing.JMenuItem itemmenucopiar;
    private javax.swing.JMenuItem itemmenurecortar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtvisor;
    // End of variables declaration//GEN-END:variables

    private double[] converte(String num1, String num2) {
       double[] d = new double[2];
        d[0] = Double.parseDouble(num1);
        d[1] = Double.parseDouble(num2);
        return d;
    }
}
